apiVersion: v1
kind: Service
metadata:
    name: "kwetterkubernetes-9a33"
    labels:
        app: "kwetterkubernetes-9a33"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kwetterkubernetes-9a33"