on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kwetterrensregistry.azurecr.io
        username: ${{ secrets.acr_kwetterrensregistry_username }}
        password: ${{ secrets.acr_kwetterrensregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kwetterrensregistry.azurecr.io/kwetterkubernetes:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kwetterrensregistry.azurecr.io/kwetterkubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kwetterkubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kwetter-frontend | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kwetter-frontend`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kwetter-frontend
        container-registry-url: kwetterrensregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_kwetterrensregistry_username }}
        container-registry-password: ${{ secrets.acr_kwetterrensregistry_password }}
        secret-name: kwetterkuberdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kwetter-frontend
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kwetterrensregistry.azurecr.io/kwetterkubernetes:${{ github.sha }}
        imagepullsecrets: |
          kwetterkuberdockerauth
